language: python
branches:
only:
  - master
python:
  - "3.7"

cache:
  directories:
      - $HOME/.pip-cache/

compiler:
  - gcc

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
        - gfortran 
        - libopenblas-dev
        - liblapack-dev
        - cmake
        - g++-7
        - gcc-7

before_install:
  - sudo chmod 777 /usr/local/bin
  - git clone https://github.com/veg/tn93.git
  - git clone https://github.com/veg/hyphy-python.git
  - export CXX="g++-7" CC="gcc-7"
  - cd tn93/ && cmake -DCMAKE_C_COMPILER=gcc-8 ./ && make install && cd ../

install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install biopython
  - pip install numpy
  - pip install cython
  - pip install -r requires.txt
  - cd hyphy-python/ && CC=gcc CXX=g++ python setup.py install && cd ../
  - travis_wait
  - pip -v install scipy
  - pip install coveralls

script: 
  - python setup.py install
  - python -c 'import hivtrace'
  - nosetests --with-coverage
notifications:
    email:
        recipients:
            - steven@stevenweaver.org
            - jwertheim@ucsd.edu
            - spond@temple.edu
        on_success: change
        on_failure: always

after_success:
  - coveralls
